blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/CodingButterBot/web-ide-display/discussions
    about: Ask questions or start discussions about the Web IDE Display project